spring.application.name=Vocabulary

spring.datasource.url=jdbc:postgresql://db.dmbuzjvezsixkrkvuskq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=BASE_strong*496*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jackson.property-naming-strategy=SNAKE_CASE

